name: "Pavlina Lejskova's Personal Website"
description: ""

url: "plejskova.github.io"

defaults:
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

permalink: /blog/:year/:month/:day/:title